version: '3.8'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=mastercard#28@@80
      - DB_NAME=grocery_db
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mastercard#28@@80
      POSTGRES_DB: grocery_db
    ports:
      - "5432:5432"